#!/bin/bash
# disable the test if GHDL is not installed on the machine

rm -f *.disabled

ghdl_bin=$(which ghdl 2> /dev/null)
if [ "x${ghdl_bin}" == "x" ]; then
    touch test_fft_case_with_simm.testdesc.disabled
fi
