#!/bin/bash

sh finalize

g++ -o data/generate_asm data/generate_asm.cc >& /dev/null
./data/generate_asm

TESTDIR=$PWD
# compile icdecoderplugin
cd ../../../../../openasip/icdecoder_plugins/ && make >& /dev/null

cd $TESTDIR
# compile the compressor plugins
cd ../../../../../openasip/compressors/ && make >& /dev/null
