#!/bin/bash

rm -f difference.txt

rm -f data/generate_asm
rm -f limm_test.tceasm

rm -f limm_test_2bus.tpef*
rm -f limm_test_3bus.tpef*
rm -f limm_test_2bus*.img
rm -f limm_test_3bus*.img

rm -f sim_in1
rm -f sim_in2

rm -rf proge-output_2bus
rm -rf proge-output_2bus_simple
rm -rf proge-output_2bus_moveslot
rm -rf proge-output_3bus
rm -rf proge-output_3bus_simple
rm -rf proge-output_3bus_moveslot

g++ -o data/generate_asm data/generate_asm.cc >& /dev/null
./data/generate_asm

TESTDIR=$PWD
# compile icdecoderplugin
cd ../../../../../tce/icdecoder_plugins/ && make >& /dev/null

cd $TESTDIR
# compile the compressor plugins
cd ../../../../../tce/compressors/ && make >& /dev/null
