#!/bin/bash

sh finalize

g++ -o data/generate_asm data/generate_asm.cc >& /dev/null
./data/generate_asm

TESTDIR=$PWD
# compile icdecoderplugin
cd ../../../../../tce/icdecoder_plugins/ && make >& /dev/null

cd $TESTDIR
# compile the compressor plugins
cd ../../../../../tce/compressors/ && make >& /dev/null
