#!/bin/bash
CURDIR=${PWD}
../../../../tce/src/codesign/osal/OSALBuilder/buildopset ${CURDIR}/data/test
../../../../tce/src/codesign/osal/OSALBuilder/buildopset ${CURDIR}/data/debug
../../../../tce/src/codesign/osal/OSALBuilder/buildopset ${CURDIR}/data/FFT_testcase
chmod +x run_*.sh
rm -f data/*.bustrace
rm -f data/*.trace.*
