#!/bin/bash
CURDIR=${PWD}
../../../../openasip/src/codesign/osal/OSALBuilder/buildopset ${CURDIR}/data/test
../../../../openasip/src/codesign/osal/OSALBuilder/buildopset ${CURDIR}/data/debug
../../../../openasip/src/codesign/osal/OSALBuilder/buildopset ${CURDIR}/data/FFT_testcase
chmod +x run_*.sh
rm -f data/*.bustrace
rm -f data/*.trace.*
rm -f .ttasim-init
