#!/bin/bash

rm -f minimal.bem
rm -f app.tpef
rm -rf proge-output-no-compression
rm -rf proge-output-InstructionDictionary
rm -rf proge-output-MoveSlotDictionary
rm -f app.img
rm -f app_data.img
rm -f minimal.adf


