DIST_OBJECTS =	SafePointer.o \
		Section.o \
		DataSection.o \
		CodeSection.o \
		SafePointable.o \
		ReferenceKey.o \
		UDataSection.o \
		SectionElement.o \
		Chunk.o \
		ASpaceElement.o \
		InstructionElement.o	

TOP_SRCDIR = ../../../..
TOOL_OBJECTS = Exception.o Conversion.o Application.o

include ${TOP_SRCDIR}/test/Makefile_configure_settings
include ${TOP_SRCDIR}/test/Makefile_test.defs
