#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2022-2026 Tampere University.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
# 
# @author 2022 Kari Hepola
#
# Python script for converting hexadecimal files to binary text format


import sys, getopt

def printHelpAndExit():
    print("Usage: oa-hex2bin -w WIDTH -o FILE_OUT FILE_IN")
    sys.exit(1)

def main(argv):
    if(len(argv) != 5):
        printHelpAndExit()

    inputfile = ''
    outputfile = ''
    width=32
    try:
        opts, args = getopt.getopt(argv,"w:o:",["outFile="])
    except getopt.GetoptError:
        printHelpAndExit()
    
    for opt, arg in opts:
        if opt == '-h':
            printHelpAndExit()
        elif opt in ("-w", "--width"):
            try:
                width = int(arg)
            except ValueError as e:
                print("Invalid width value: " + arg)
                sys.exit(1)
        elif opt in ("-o", "--outfile"):
            outputfile = arg

    inputfile = argv[4]

    hexfile = open(inputfile, 'r')
    binfile = open(outputfile, 'w')

    for line in hexfile:
        line = line.rstrip()
        if len(line) > width/4 :
            print("Error: Minimum width of: "
            + str(len(line)*4) + " required")
            sys.exit(1)
        try:
            hexValue = (int(line, 16))
        except ValueError as e:
            print("Error: Invalid hex value"
            ", make sure input file is in hex format!")
            print(e)
            sys.exit(1)

        # zerofill to the correct width
        binValue = (bin(hexValue)[2:]).zfill(width)
        binfile.write(binValue)
        binfile.write('\n')

    hexfile.close()
    binfile.close()


if __name__ == "__main__":
   main(sys.argv[1:])

