#!/bin/sh
# Copyright (c) 2002-2011 Tampere University of Technology.
#
# This file is part of TTA-Based Codesign Environment (TCE).
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#
# Creates BEM of the given ADF and prints most essential info of the
# instruction and move slot sizes.
#
# Usage: machine_instruction_info machine.adf
#
# author 2011 Otto Esko

BEM=`mktemp /tmp/machXXXX.bem`

function print_usage() {
   echo "Usage: $0 <adf>"
}

function eexit() {
   echo $1
   rm -f $BEM
   exit 1
}

FILTER="Total instruction.*|Move Slot:.*|Width:.*|src field:.*"

if [ $# -ne 1 ]; then
   print_usage
   eexit ""
fi

ADF=$1
if [ ! -e $1 ]; then
   eexit "ADF $1 does not exist"
fi

createbem -o $BEM $ADF || eexit "Failed to create BEM"
viewbem $BEM | grep -E "$FILTER" | sed 's/^Move Slot:/\n&/g'
echo ""
rm -f $BEM
exit 0
