#!/usr/bin/env python3
# -*- coding: utf-8
# Copyright (c) 2002-2022 Tampere University.
#
# This file is part of TTA-Based Codesign Environment (TCE).
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#
# Runs basic tests to verify a TCE installation (installed somewhere in PATH)
# works.
#
# Does not test the functionality of the tools, just ensures the tools can
# be executed and do what they are expected to do from installation paths.
# It's sort of a "smoke test" that tells whether there is something seriously
# broken with the TCE installation.
#
# (C) 2009-2019 Pekka Jääskeläinen
#     2022      Kari Hepola

# Deprecated just calls the new self test script oa-selftest

import os, sys
argList=sys.argv[1:]
os.system('oa-selftest %s' % ' '.join(argList))