#!/bin/bash
rm -rf ExpRes.dsdb
rm -rf complex_multiply.{{a,i}df,bem}
rm -rf data/program.bc
rm -rf complex_multiply.tpef
rm -rf complex_multiply.img
rm -rf complex_multiply_data.img
rm -rf debug.log
rm -rf proge-output
