#!/bin/bash
rm -rf ExpRes.dsdb
rm -rf ?.{{a,i}df,bem}
rm -rf data/program.bc
rm -rf complex_multiply.scheduled.tpef
rm -rf complex_multiply.scheduled.img
rm -rf complex_multiply.scheduled_data.img
rm -rf debug.log
rm -rf proge-output

# Compile the initial machine generator estimator plugin.
pushd . > /dev/null
cd ../../../../../tce/explorer/ 
# rm -f *.so
if [ ! -e "SimpleICOptimizer.so" ]; then 
    ../src/codesign/Explorer/buildexplorerplugin SimpleICOptimizer.so SimpleICOptimizer.cc > /dev/null
fi
if [ ! -e "RemoveUnconnectedComponents.so" ]; then 
    ../src/codesign/Explorer/buildexplorerplugin RemoveUnconnectedComponents.so RemoveUnconnectedComponents.cc > /dev/null
fi
if [ ! -e "ImplementationSelector.so" ]; then 
    ../src/codesign/Explorer/buildexplorerplugin ImplementationSelector.so ImplementationSelector.cc > /dev/null
fi
popd > /dev/null
