#!/usr/bin/env python
#-*- coding: utf-8 -*-
# 
# Copyright (c) 2011 Tampere University of Technology.
#
# This file is part of TTA-Based Codesign Environment (TCE).
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#
# @author Pekka Jääskeläinen 2011
#
# Compiler driver for the Cell SPU that utilizes LLVM and the 
# TCE instruction scheduling framework.
#
#  Usage: tcecc-spu module1.c module2.c -o module
#
import sys
import os.path
import tempfile
from optparse import OptionParser

script_dir = os.path.dirname(sys.argv[0])
fixed_adf_dir = script_dir + "/fixed-adf"
if sys.platform == "darwin":
    lib_tce = script_dir + "/../../.libs/libtce.dylib"
else:
    lib_tce = script_dir + "/../../.libs/libtce.so"

def run_command(command, echoStderr=True, echoStdout=True, echoCmd=False):
    """Runs the given shell command and returns its exit code.

    If echoOutput is False, stdout and stderr are redirected to /dev/null."""
    
    from subprocess import Popen, PIPE
   
    if echoCmd:
        print command

    if not echoStdout:
        stdoutRedir = open('/dev/null', 'w')
        stdoutFD = stdoutRedir.fileno()
    else:
        stdoutFD = None

    if not echoStderr:
        stderrRedir = open('/dev/null', 'w')
        stderrFD = stderrRedir.fileno()
    else:
        stderrFD = None

    process = \
       Popen(command, shell=True, stdin=PIPE, stdout=stdoutFD,
             stderr=stderrFD, close_fds=False)
    return process.wait()

tempfiles = []

def create_temp_file(suffix=""):
    if options.leave_tempfiles:
        tf = tempfile.mkstemp(suffix=suffix, dir=os.getcwd())[1]
    else:
        tf = tempfile.mkstemp(suffix=suffix)[1]
    tempfiles.append(tf)
    return tf

def cleanup_and_exit(retval=0):
    if not options.leave_tempfiles:
        for tf in tempfiles:
            os.unlink(tf)
    sys.exit(retval)

def parse_options():
    parser = OptionParser()
    parser.add_option("-o", "--output", dest="output",
                      help="The output file.", metavar="FILE",
                      default=None)
    parser.add_option("-a", "--adf", dest="adf",
                      help="The TCE architecture description format file used for configuring the scheduler.", 
                      metavar="FILE", default=fixed_adf_dir + "/cellspu.adf")
    parser.add_option("-S", "--compile-only", dest="compile_only",
                      action="store_true", default=False,
                      help="Compile only. Do not assemble or link.")
    parser.add_option("", "--no-tce-scheduler", dest="use_tce_scheduler",
                      action="store_false", default=True,
                      help="Do not use the TCE instruction scheduler.")
    parser.add_option("", "--leave-tempfiles", dest="leave_tempfiles",
                      action="store_true", default=False,
                      help="Do not delete the temporary files.")
    parser.add_option("-v", "--verbose", dest="verbose", action="store_true",
                      help="Verbose output. Output the commands executed etc.", default=False)
    parser.add_option("", "--dump-ddgs", dest="dump_ddgs",
                      action="store_true", default=False,
                      help="Write out Data Dependence Graphs for processed functions.")
    parser.add_option("", "--dump-ddgs-dot", dest="dump_ddgs_dot",
                      action="store_true", default=False,
                      help="Write out Data Dependence Graphs for processed functions.")
    parser.add_option("", "--dump-ddgs-xml", dest="dump_ddgs_xml",
                      action="store_true", default=False,
                      help="Write out Data Dependence Graphs for processed functions.")
    parser.add_option("", "--disable-llvmaa", dest="disable_llvmaa",
                      action="store_true", default=False,
                      help="Disable use of LLVM Alias Analysis in code generation.")

    (options, args) = parser.parse_args()
    return (options, args)

def compile_to_bitcode(input_files):    
    bc_files = []
    for input_file in input_files:
        bc_file = create_temp_file(input_file.replace("/", ".") + ".bc")
        retval = \
            run_command("clang -target cellspu-v0 -O3 -c -emit-llvm %s -o %s" % \
                        (input_file, bc_file), echoCmd=options.verbose)
        if retval != 0: cleanup_and_exit(retval)
        bc_files.append(bc_file)

    bc_file = create_temp_file(".whole-program.bc")

    retval = run_command("llvm-link %s -o %s" % (" ".join(bc_files), bc_file), echoCmd=options.verbose)
    if retval != 0: cleanup_and_exit(retval)

    return bc_file

def generate_code(bc_file, adf, output=None):
    if output is None:
        asm_file = create_temp_file(".S")
    else:
        asm_file = output
    dump_options = ""
    llvmaa_options = ""
    if options.dump_ddgs:
        dump_options = "--dump-ddgs"
    if options.dump_ddgs_dot:
        dump_options = "--dump-ddgs-dot"
    if options.dump_ddgs_xml:
        dump_options = "--dump-ddgs-xml"
    if options.disable_llvmaa:
        llvmaa_options = "--disable-llvmaa"        
    if options.use_tce_scheduler:
        retval = run_command("llc -load %s -adf %s %s -o %s %s %s" % (lib_tce, adf,  bc_file, asm_file, dump_options, llvmaa_options), 
                             echoStdout=True, echoCmd=options.verbose)
    else:
        retval = run_command("llc %s -o %s" % (bc_file, asm_file), echoStdout=True, echoCmd=options.verbose)
    if retval != 0: cleanup_and_exit(retval)
    return asm_file

def assemble(asm_file):
    obj_file = create_temp_file(".o")
    # Here the tool (assembler) varies per target. Currently only SPU supported,
    # later we could call tceasm for TCE here etc.
    retval = run_command("spu-as %s -o %s" % (asm_file, obj_file), echoCmd=options.verbose)
    if retval != 0: cleanup_and_exit(retval)
    return obj_file


def link(obj_files, output):
    retval = run_command("spu-gcc %s -o %s" % (" ".join(obj_files), output), echoCmd=options.verbose)
    if retval != 0: cleanup_and_exit(retval)
    return output

if __name__ == "__main__":
    options, args = parse_options()

    final_output = options.output
    if options.output is None:
        pieces = args[0].split(".")
        if len(pieces) > 0:
            input_without_extension = ".".join(pieces[0:-1])
        else:
            input_without_extension = args[0]
        if options.compile_only:
            final_output = input_without_extension + ".s"
        else:
            final_output = "a.out"

    bc_file = compile_to_bitcode(args)
    if options.compile_only:
        generate_code(bc_file, options.adf, final_output)
    else:
        asm_file = generate_code(bc_file, options.adf)
        obj_file = assemble(asm_file)
        link([obj_file], final_output)
    cleanup_and_exit(0)
