DIST_OBJECTS = 	TPEFProgramFactory.o Program.o Instruction.o Move.o \
		MoveGuard.o Address.o Procedure.o TerminalRegister.o \
		TerminalImmediate.o NullInstruction.o NullMoveGuard.o \
		TerminalFUPort.o NullMove.o Immediate.o NullTerminal.o \
		NullImmediate.o NullAddress.o NullProcedure.o Terminal.o \
		NullProgram.o Scope.o GlobalScope.o Label.o CodeLabel.o \
	    DataLabel.o InstructionReference.o \
		InstructionReferenceManager.o TerminalAddress.o \
		TerminalInstructionAddress.o \
		NullInstructionReferenceManager.o \
		NullGlobalScope.o ProgramWriter.o \
		DataMemory.o DataDefinition.o DataAddressDef.o \
		DataInstructionAddressDef.o \
		AnnotatedInstructionElement.o ProgramAnnotation.o 


TPEF_OBJECTS = *.o
MACH_OBJECTS = *.o
TOOL_OBJECTS = *.o
OSAL_OBJECTS = *.o
UMACH_LIB_OBJS = *.o
DISASSEMBLER_LIB_OBJS = *.o
APPLIBS_MACH_OBJS = ResourceVector.o ResourceVectorSet.o

TOP_SRCDIR = ../../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings

include ${TOP_SRCDIR}/test/Makefile_test.defs
