TOP_SRCDIR = ../../..
include ${TOP_SRCDIR}/test/Makefile_configure_settings

CPPFLAGS+=${BOOST_INCLUDES}
DIST_OBJECTS = TextGenerator.o Exception.o Conversion.o Application.o



include ${TOP_SRCDIR}/test/Makefile_test.defs
