#!/bin/bash
#
# Generates the TraceDB used in an Estimator system test.
# TraceDB is generated by running Simulation with tracing
# options on.
rm -f data/worm.tpef.trace*
{
../../../../tce/src/codesign/ttasim/ttasim <<EOF
setting execution_trace on
setting rf_tracking on
setting bus_trace on
setting utilization_data_saving on
mach data/worm.adf
prog data/worm.tpef
disassemble
stepi 10
quit
EOF
} >/dev/null

exit

sqlite3 data/worm.tpef.trace <<EOF
.echo ON
SELECT * FROM bus_activity;
SELECT * FROM register_file_access;
SELECT * FROM fu_operation_triggers;
SELECT * FROM totals;
SELECT * FROM socket_write_counts;
SELECT * FROM bus_write_counts;
EOF
