#!/bin/bash
CURDIR=$(pwd)
cd $CURDIR

./generate_hdb.sh
./generate_tracedb.sh
# Test with:
# ../../../../openasip/src/codesign/Estimator/estimate -p data/worm.tpef -t data/worm.tpef.trace data/worm.adf data/worm.idf
