#!/bin/bash
# Creates a new Debian package from the current source tree and 
# deletes all older packages from the tce/ directory.
#
# Good starting point for information:
# http://www.ibm.com/developerworks/linux/library/l-debpkg.html

function eexit {
    echo "$1"
    cleanup
    exit 1
}

function cleanup {
    rm -fr $tempDir
}

tceRoot=../../../

# Grab the tce bzr revision number
oldDir=$(pwd)
cd ${tceRoot}
version="$(bzr revno)"
cd $oldDir

echo "Creating a .deb for TCE version bzr ${version}."

tempDir=$(mktemp -d)
echo "Temporary directory for the package: ${tempDir}"

mkdir $tempDir/DEBIAN
cp DEBIAN/* $tempDir/DEBIAN

echo "Building and installing TCE."

cd $tceRoot
export CXX="ccache g++"
export CC="ccache gcc"
export CXXFLAGS="-O3 -g" 
./configure --enable-distributed || eexit "configure failed."
make DESTDIR=$tempDir dev-install || eexit "make failed."

cat > $tempDir/DEBIAN/control <<EOF
Package: tce1.0
Version: ${version}
Section: devel 
Priority: optional
Architecture: i386
Essential: no
Depends: libwxgtk2.6-0, libboost-filesystem1.34.1,
         libboost-graph1.34.1, libboost-regex1.34.1, \
         libboost-thread1.34.1, tcl8.5, libedit2, \
         libsqlite3-0, libxerces27, g++, tce-frontend1.0
Pre-Depends: perl 
Recommends: llvm (=2.1)
Suggests: kpdf | acroread | evince, sqlite3
Installed-Size: $(du -s $tempDir/usr | awk '{print $1}')
Maintainer: Pekka Jaaskelainen <pekka.jaaskelainen@tut.fi>
Provides: tce1.0
Description: TTA Co-design Environment. A toolset for designing TTA-based systems.
EOF

# delete the old .deb files
rm *.deb

# create the new .deb
package=tce-1.0_${version}_i386.deb

rm -f $package
dpkg -b $tempDir $package || eexit "building package with dpkg failed."

cleanup
