#!/bin/bash
# Creates a new Debian package from the current source tree and 
# deletes all older packages from the tce/ directory.
#
# Good starting point for information:
# http://www.ibm.com/developerworks/linux/library/l-debpkg.html

tceRoot=../../../

#version=$1


# Grab the tce svn revision number
oldDir=$(pwd)
cd ~/tce
version="$(svn info | grep "Last Changed Rev"| awk '{print $4}')"
cd $oldDir

# OLD:
#if [ "_$version" == "_" ]; then
#    echo "Please give version string (e.g. 1.0beta1) as the argument."
#    exit 1
#fi

echo "Creating a .deb for TCE version svn${version}."

tempDir=$(mktemp -d)
echo "Temporary directory for the package: ${tempDir}"

mkdir $tempDir/DEBIAN
cp DEBIAN/* $tempDir/DEBIAN

echo "Building and installing TCE."

cd $tceRoot
CXXFLAGS="-O3 -g" ./configure && make DESTDIR=$tempDir install || exit 2

cat > $tempDir/DEBIAN/control <<EOF
Package: tce
Version: ${version}
Section: devel 
Priority: optional
Architecture: i386
Essential: no
Depends: libwxgtk2.6-0, libboost-filesystem1.33.1, libboost-graph1.33.1, libboost-regex1.33.1, tcl8.4, libedit2, libsqlite3-0, libxerces27, g++
Pre-Depends: perl 
Suggests: kpdf | acroread | evince, sqlite3
Installed-Size: $(du -s $tempDir/usr | awk '{print $1}')
Maintainer: Pekka Jaaskelainen <pekka.jaaskelainen@tut.fi>
Provides: tce
Description: TTA Co-design Environment. A toolset for designing TTA-based systems.
EOF

# delete the old .deb files
rm *.deb

# create the new .deb
package=tce_svn${version}_i386.deb

rm -f $package
dpkg -b $tempDir $package || exit 3

rm -fr $tempDir

