#!/bin/bash
# Creates a new Debian package from the current source tree and 
# deletes all older packages from the tce/ directory.
#
# Good starting point for information:
# http://www.ibm.com/developerworks/linux/library/l-debpkg.html
#
# $1    package version number, default TCE_ROOT bzr revision

TCE_ROOT=${TCE_ROOT:-"../../../"}
DEB_ARCH=${DEB_ARCH:-"i386"}
PROGRAM_NAME=${PROGRAM_NAME:-"tce"}

function eexit {
    echo "$1"
    cleanup
    exit 1
}

function cleanup {
    rm -fr $TMP_DIR
}

# adds the $1 param to the end of PATH variable
function addToPath {
    local re='[:\n]{1}'
    if [ -z "$(echo "$PATH" | grep -E "${1}${re}")" ]; then
        export PATH="${PATH}:${1}"
    fi  
}

function init_temp_dir {
    TMP_DIR=$(mktemp -d)
    echo "Temporary directory for the package: ${TMP_DIR}"

    mkdir $TMP_DIR/DEBIAN
    cp DEBIAN/* $TMP_DIR/DEBIAN
}

function build_and_install {
    local log_file="/dev/null"
    export LLVM_BIN_DIR=${LLVM_BIN_DIR:-$HOME/llvm/bin}
    export LLVM_FRONTEND_INSTALL_DIR=${LLVM_FRONTEND_INSTALL_DIR:-$HOME/llvm-frontend}
    addToPath "${LLVM_BIN_DIR}"
    addToPath "${LLVM_FRONTEND_INSTALL_DIR}/bin"

    export CXX="g++"
    export CC="gcc"
    export CXXFLAGS="-O3 -g" 

    cd $TCE_ROOT
    make clean > ${log_file}
    ./configure --enable-distributed > ${log_file} || eexit "configure failed."
    make DESTDIR=${TMP_DIR} dev-install > ${log_file} || eexit "make failed."
}

function create_deb {
    # create the new .deb
    local package=${PROGRAM_NAME}-${VERSION}_${DEB_ARCH}.deb

    # remove old packages
    rm -rf *.deb
    dpkg -b $TMP_DIR $package || eexit "building package with dpkg failed."
}


### MAIN ###

# package version given as a parameter or 
if [ "${1}x" != "x" ]; then
    VERSION="${1}"
else
    VERSION="$(bzr revno $TCE_ROOT)"
fi

echo "Creating a .deb for TCE with version: ${VERSION}"

init_temp_dir

echo "Building and installing TCE."

build_and_install

cat > $TMP_DIR/DEBIAN/control <<EOF
Package: tce
Version: ${VERSION}
Section: devel 
Priority: optional
Architecture: ${DEB_ARCH}
Essential: no
Depends: libwxgtk2.6-0, libboost-filesystem1.34.1, \
libboost-graph1.34.1, libboost-regex1.34.1, \
libboost-thread1.34.1, tcl8.5, libedit2, \
libsqlite3-0, libxerces27, g++, \
tce-frontend
Pre-Depends: perl 
Recommends: llvm (=2.2)
Suggests: kpdf | acroread | evince, sqlite3
Installed-Size: $(du -s $TMP_DIR/usr | awk '{print $1}')
Maintainer: Pekka Jaaskelainen <pekka.jaaskelainen_no.spam_tut.fi>
Provides: tce
Description: TTA Co-design Environment. A toolset for designing TTA-based application specific processors.
EOF

create_deb

cleanup
