
# relative path to Makefile definitions and shared latex/bibtex files
DEFS = ../../../latexdefs

# document title (extended document name) - must be double quoted!
DOC_NAME_TEXT = "The Graph Framework"

# options passed to latex command
LATEX_OPTS = -interaction=batchmode

# default rule built by Makefile
BUILD_DEFAULT = pdf


include $(DEFS)/Makefile.defs

# Name of the latex class file for this document (with relative path).
# Remove this for testing, requirement or design documents.
# CLASS_PATH is required for architecture design documents and manuals.
# CLASS_PATH = $(DEFS)/manual.cls
