DIST_OBJECTS = Program.o NullProgram.o Procedure.o NullProcedure.o \
	Instruction.o NullInstruction.o Immediate.o NullImmediate.o Move.o \
	NullMove.o Terminal.o NullTerminal.o MoveGuard.o NullMoveGuard.o \
	Scope.o GlobalScope.o Label.o CodeLabel.o DataLabel.o Address.o \
	NullAddress.o InstructionReferenceManager.o \
    NullGlobalScope.o NullInstructionReferenceManager.o \
	DataMemory.o DataDefinition.o DataAddressDef.o \
	DataInstructionAddressDef.o \
    InstructionReference.o TerminalImmediate.o TerminalAddress.o \
	AnnotatedInstructionElement.o ProgramAnnotation.o 

TOOL_OBJECTS = *.o
MACH_OBJECTS = *.o
OSAL_OBJECTS = *.o
UMACH_LIB_OBJS = *.o
APPLIBS_MACH_OBJS = ResourceVector.o ResourceVectorSet.o

TOP_SRCDIR = ../../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings

include ${TOP_SRCDIR}/test/Makefile_test.defs
