#!/bin/bash
../../../../tce/src/codesign/osal/OSALBuilder/buildopset ../../../../tce/scheduler/testbench/Operations/ShiftRows
ln -sf ../../../../../tce/scheduler/testbench/Operations/ShiftRows.opp data/ShiftRows.opp
ln -sf ../../../../../tce/scheduler/testbench/Operations/ShiftRows.opb data/ShiftRows.opb
ln -sf ../../../../tce/scheduler/testbench/Operations OpenCL/example1/data
ln -sf ../../../../tce/scheduler/testbench/Operations OpenCL/oclAESGladman/data

if `../../../../tce/src/bintools/Compiler/tcecc --supported-languages |grep -q "OpenCL C"`
then
    rm -f OpenCL.testdesc.disabled
else
    touch OpenCL.testdesc.disabled
fi
