#!/bin/bash
../../../../tce/src/codesign/osal/OSALBuilder/buildopset ../../../../tce/scheduler/testbench/Operations/ShiftRows
ln -sf ../../../../../tce/scheduler/testbench/Operations/ShiftRows.opp data/ShiftRows.opp
ln -sf ../../../../../tce/scheduler/testbench/Operations/ShiftRows.opb data/ShiftRows.opb
ln -sf ../../../../tce/scheduler/testbench/Operations OpenCL/example1/data
ln -sf ../../../../tce/scheduler/testbench/Operations OpenCL/oclAESGladman/data

llvm_version=`llvm-config --version`

if test "x${llvm_version}" != "x2.9" -a -a "../../../../tce/src/bintools/Compiler/pocl"
then
    rm -f OpenCL.testdesc.disabled
else
    touch OpenCL.testdesc.disabled
fi

