#!/bin/bash
CURDIR=$(pwd)
rm -rf testi.dsdb
rm -rf sim.tpef
rm -rf ttasim_output.temp

# Compile the initial machine generator estimator plugin.
pushd . > /dev/null
cd ../../../../explorer/ && rm -f *.so
../src/codesign/Explorer/buildexplorerplugin MinimizeMachine.so MinimizeMachine.cc > /dev/null
popd > /dev/null

# Compile the IC&decoder estimator plugin.
#pushd . > /dev/null
#cd ../../../icdecoder_plugins/ && rm -f *.so
#../src/procgen/ProGe/buildicdecoderplugin DefaultICDecoderPlugin.so DefaultICDecoderPlugin.cc DefaultDecoderGenerator.cc DefaultICGenerator.cc CentralizedControlICGenerator.cc > /dev/null
#popd > /dev/null

# Compile the FU estimator plugin.
#pushd . > /dev/null
#cd ../../../cost_estimator_plugins/fu/ && rm -f *.so
#make > /dev/null
#popd > /dev/null

# Compile the RF estimator plugin.
#pushd . > /dev/null
#cd ../../../cost_estimator_plugins/rf/ && rm -f *.so
#make > /dev/null
#popd > /dev/null

