#!/bin/bash
# disable the test if GHDL is not installed on the machine
rm -rf *.disabled
ghdl_bin=$(which ghdl 2> /dev/null)
if [ "x${ghdl_bin}" != "x" ]; then

    true
#    These are already compiled with the build.
#    bash compile_dictionary_compressor.sh > /dev/null
#    cd ../../../../tce/icdecoder_plugins
#    ../src/procgen/ProGe/buildicdecoderplugin DefaultICDecoderPlugin.so \
#    DefaultICDecoderPlugin.cc DefaultDecoderGenerator.cc \
#    DefaultICGenerator.cc CentralizedControlICGenerator.cc > /dev/null

else
    touch test_fft_case_with_limm.testdesc.disabled
    touch test_fft_case_with_simm.testdesc.disabled
    touch test_fft_case_with_limm_opt.testdesc.disabled
    touch test_fft_case_with_compression.testdesc.disabled
    touch verify_limm_operation.testdesc.disabled
fi
