#!/bin/bash
CURDIR=$(pwd)
rm -rf simple_test.dsdb
rm -rf ?.adf
rm -rf ttasim_output

# Compile the initial machine generator estimator plugin.
pushd . > /dev/null
cd ../../../../../tce/explorer/ && rm -f *.so
if [ ! -e "SimpleICOptimizer.so" ]; then 
    ../src/codesign/Explorer/buildexplorerplugin SimpleICOptimizer.so SimpleICOptimizer.cc > /dev/null
fi
if [ ! -e "RemoveUnconnectedComponents.so" ]; then 
    ../src/codesign/Explorer/buildexplorerplugin RemoveUnconnectedComponents.so RemoveUnconnectedComponents.cc > /dev/null
fi
popd > /dev/null

# Compile the IC&decoder estimator plugin.
#pushd . > /dev/null
#cd ../../../../tce/icdecoder_plugins/ && rm -f *.so
#../src/procgen/ProGe/buildicdecoderplugin DefaultICDecoderPlugin.so DefaultICDecoderPlugin.cc DefaultDecoderGenerator.cc DefaultICGenerator.cc CentralizedControlICGenerator.cc > /dev/null
#popd > /dev/null

# Compile the FU estimator plugin.
#pushd . > /dev/null
#cd ../../../../tce/cost_estimator_plugins/fu/ && rm -f *.so
#make > /dev/null
#popd > /dev/null

# Compile the RF estimator plugin.
#pushd . > /dev/null
#cd ../../../../tce/cost_estimator_plugins/rf/ && rm -f *.so
#make > /dev/null
#popd > /dev/null

