#!/bin/bash
# disable the test if GHDL is not installed on the machine
rm -rf *.disabled
ghdl_bin=$(which ghdl 2> /dev/null)
if [ "x${ghdl_bin}" != "x" ]; then
    exit 0
else
    touch test_default_hdb.testdesc.disabled
fi
