OBJECTS = OperationContext.o OperationPool.o Operation.o InstructionFormat.o RISCVTools.o \
Machine.o BEMGenerator.o BinaryEncoding.o RISCVFields.o InstructionExecutor.o

TOP_SRCDIR = ../../../..
include ${TOP_SRCDIR}/test/Makefile_test.defs



CXXFLAGS += -g3 -O0 -fno-inline -fno-omit-frame-pointer
LDFLAGS += -g3