DIST_OBJECTS = Exception.o  CmdLineOptions.o CmdLineParser.o \
CmdLineOptionParser.o Options.o OptionValue.o
TOOL_OBJECTS = Conversion.o Application.o
TOP_SRCDIR = ../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings
include ${TOP_SRCDIR}/test/Makefile_test.defs
