#!/bin/bash
# Creates a new Debian package from the current LLVM frontend and 
# deletes all older packages from the same directory.
#
# Good starting point for information:
# http://www.ibm.com/developerworks/linux/library/l-debpkg.html

function eexit {
    echo "${1}"
    rm -rf "$tempDir"
    exit 1
}


cd ..

# Grab the bzr revision number
version="$(bzr revno)"

echo "Creating a .deb for LLVM frontend version bzr ${version}."

tempDir=$(mktemp -d)
echo "Temporary directory for the package: ${tempDir}"

mkdir $tempDir/DEBIAN
cp scripts/DEBIAN/* $tempDir/DEBIAN

echo "Building and installing LLVM into temp dir."

mkdir llvm-gcc-build
cd llvm-gcc-build

export MAKEFLAGS=-j1
export CXX=g++
export CXXFLAGS="-O2"
export CFLAGS="-O2"
export CC=gcc

export INSTALLATION_PATH=$HOME/tce-installation
export LLVM_BIN_DIR=${HOME}/llvm/bin
export LLVM_FRONTEND_INSTALL_DIR=${HOME}/llvm-frontend

export PATH="$INSTALLATION_PATH/bin:${LLVM_BIN_DIR}:${INSTALLATION_PATH}/bin:${LLVM_FRONTEND_INSTALL_DIR}/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin"
export LD_LIBRARY_PATH=$INSTALLATION_PATH/lib

../configure || eexit "Configure failed."
make || eexit "Make failed."
make DESTDIR=$tempDir install || eexit "Make install failed."

cd ..

# Create the .deb control file
cat > $tempDir/DEBIAN/control <<EOF
Package: tce-frontend
Version: ${version}
Section: devel 
Priority: optional
Architecture: i386
Essential: no
Depends: binfmt-support, libc6, libgcc1, libstdc++6
Pre-Depends: perl 
Installed-Size: $(du -s $tempDir/usr | awk '{print $1}')
Maintainer: Pekka Jaaskelainen <pekka.jaaskelainen@tut.fi>
Provides: tce-frontend
Description: Low-Level Virtual Machine (LLVM) C/C++ compiler for TCE
EOF
#Conflicts: llvm

# delete the old .deb files
rm *.deb

# create the new .deb
package=llvm_tce_bzr${version}_i386.deb

rm -f $package
dpkg -b $tempDir $package || eexit "dpkg -b $tempDir failed." 

rm -fr $tempDir
