#!/bin/bash
rm -rf *.disabled
ghdl_bin=$(which ghdl 2> /dev/null)
if [ "x${ghdl_bin}" != "x" ]; then
    cd ../../../../tce/icdecoder_plugins
    make -s > /dev/null
else
    touch function_pointer.testdesc.disabled
    touch tcetest_data_image_padding.sh.disabled
fi

