TOP_SRCDIR = ../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings 

DIST_OBJECTS = SimValue.o
TOOL_OBJECTS = Application.o ObjectState.o Exception.o Conversion.o

include ${TOP_SRCDIR}/test/Makefile_test.defs
