#!/bin/bash
rm -rf ./proge-output
rm -rf ./proge-output-sockets
rm -fr shared-vhdl
rm -rf ./proge-output-funame
rm -rf ./proge-output-lsuport
rm -f funame_test_data.img funame_test.img funame_test.tpef
rm -f *.img *.tpef
