#!/bin/bash
rm -rf ./proge-output
rm -rf ./proge-output-sockets
rm -fr shared-vhdl
rm -rf ./proge-output-funame
rm -rf ./proge-output-lsuport
rm -f funame_test_data.img funame_test.img funame_test.tpef
rm -f *.img *.tpef

ghdl_bin=$(which ghdl 2> /dev/null)
if [ "x${ghdl_bin}" == "x" ]; then
    touch tcetest_sram_rf.sh.disabled
else
    rm -f tcetest_sram_rf.sh.disabled
fi

ln -s ../../../codesign/tce_tour/data/tutorial.opp data/tutorial.opp