/*
    Copyright 2002-2008 Tampere University of Technology.  All Rights
    Reserved.

    This file is part of TTA-Based Codesign Environment (TCE).

    TCE is free software; you can redistribute it and/or modify it under the
    terms of the GNU General Public License version 2 as published by the Free
    Software Foundation.

    TCE is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
    details.

    You should have received a copy of the GNU General Public License along
    with TCE; if not, write to the Free Software Foundation, Inc., 51 Franklin
    St, Fifth Floor, Boston, MA  02110-1301  USA

    As a special exception, you may use this file as part of a free software
    library without restriction.  Specifically, if other files instantiate
    templates or use macros or inline functions from this file, or you compile
    this file and link it with other files to produce an executable, this
    file does not by itself cause the resulting executable to be covered by
    the GNU General Public License.  This exception does not however
    invalidate any other reasons why the executable file might be covered by
    the GNU General Public License.
*/
/**
 * @file ResultDialog.cc
 *
 * Definition of ResultDialog class.
 *
 * @author Jussi Nykänen 2004 (nykanen-no.spam-cs.tut.fi)
 * @note rating: red
 */

#include <boost/format.hpp>

#include "ResultDialog.hh"
#include "OSEdTextGenerator.hh"
#include "GUITextGenerator.hh"
#include "WxConversion.hh"
#include "WidgetTools.hh"
#include "DialogPosition.hh"
#include "ErrorDialog.hh"
#include "CommandThread.hh"
#include "FileSystem.hh"
#include "OSEd.hh"

using boost::format;
using std::string;
using std::vector;

BEGIN_EVENT_TABLE(ResultDialog, wxDialog)
    EVT_BUTTON(ID_BUTTON_OPEN, ResultDialog::onOpen)
END_EVENT_TABLE()

/**
 * Constructor.
 *
 * @param parent Parent window.
 */
ResultDialog::ResultDialog(
    wxWindow* parent, 
    std::vector<std::string> output,
    const std::string& title,
    const std::string& module) :
    wxDialog(parent, -1, _T(""), 
             DialogPosition::getPosition(DialogPosition::DIALOG_RESULT),
             wxDefaultSize, wxRESIZE_BORDER), 
    output_(output), module_(module) {

    createContents(this, true, true);
    result_ = dynamic_cast<wxTextCtrl*>(FindWindow(ID_RESULT));
    result_->SetEditable(false);

    FindWindow(wxID_OK)->SetFocus();
	SetTitle(WxConversion::toWxString(title));
    if (module_ == "") {
        FindWindow(ID_BUTTON_OPEN)->Disable();
    }
    setTexts();
}

/**
 * Destructor.
 */
ResultDialog::~ResultDialog() {
    int x, y;
    GetPosition(&x, &y);
    wxPoint point(x, y);
    DialogPosition::setPosition(DialogPosition::DIALOG_RESULT, point);
}

/**
 * Set texts to widgets.
 */
void
ResultDialog::setTexts() {
	
    GUITextGenerator& guiText = *GUITextGenerator::instance();
    OSEdTextGenerator& osedText = OSEdTextGenerator::instance();

    // buttons
    WidgetTools::setLabel(&guiText, FindWindow(wxID_OK),
                          GUITextGenerator::TXT_BUTTON_OK);
    
    WidgetTools::setLabel(&osedText, FindWindow(ID_BUTTON_OPEN),
                          OSEdTextGenerator::TXT_BUTTON_OPEN);
}

/**
 * Transfer data to window.
 *
 * @return True if transfer is successful.
 */
bool
ResultDialog::TransferDataToWindow() {
    for (size_t i = 0; i < output_.size(); i++) {
        result_->AppendText(WxConversion::toWxString(output_[i]));
    }
    return wxWindow::TransferDataToWindow();
}

/**
 * Handles the event when Open button is pushed.
 */
void
ResultDialog::onOpen(wxCommandEvent&) {
    
    OSEdTextGenerator& texts = OSEdTextGenerator::instance();
    OSEdOptions* options = wxGetApp().options();
    string editor = options->editor();
    if (editor == "") {
        format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_NO_EDITOR);
        ErrorDialog error(this, WxConversion::toWxString(fmt.str()));
        error.ShowModal();
    } else {
        if (FileSystem::fileExists(editor)) {
            string cmd = editor + " " + module_;
            CommandThread* thread = new CommandThread(cmd);
            thread->Create();
            thread->Run();
        } else {
            format fmt = texts.text(OSEdTextGenerator::TXT_ERROR_OPEN);
            fmt % editor;
            ErrorDialog dialog(this, WxConversion::toWxString(fmt.str()));
            dialog.ShowModal();
        }
    }
}

/**
 * Creates the contents of the dialog.
 *
 * NOTE! This function was generated by wxDesigner.
 *
 * @param parent Parent window.
 * @param call_fit If true fits the contents inside the dialog.
 * @param set_sizer If true, sets the main sizer as contents of dialog.
 * @return The created sizer.
 */
wxSizer*
ResultDialog::createContents(
    wxWindow *parent, 
    bool call_fit, 
    bool set_sizer) {

    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxTextCtrl *item1 = new wxTextCtrl( parent, ID_RESULT, wxT(""), wxDefaultPosition, wxSize(400,100), wxTE_MULTILINE );
    item0->Add( item1, 1, wxGROW|wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item3 = new wxButton( parent, ID_BUTTON_OPEN, wxT("Open"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, wxID_OK, wxT("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}
