#OSALBUILDER=~/tce/src/codesign/osal/OSALBuilder/buildopset
OSALBUILDER=buildopset
simulator_test_operations.opb: \
	simulator_test_operations.cc simulator_test_operations.opp
	${OSALBUILDER} simulator_test_operations

clean:
	rm -f *.opb