/*
    Copyright 2002-2008 Tampere University of Technology.  All Rights
    Reserved.

    This file is part of TTA-Based Codesign Environment (TCE).

    TCE is free software; you can redistribute it and/or modify it under the
    terms of the GNU General Public License version 2 as published by the Free
    Software Foundation.

    TCE is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
    details.

    You should have received a copy of the GNU General Public License along
    with TCE; if not, write to the Free Software Foundation, Inc., 51 Franklin
    St, Fifth Floor, Boston, MA  02110-1301  USA

    As a special exception, you may use this file as part of a free software
    library without restriction.  Specifically, if other files instantiate
    templates or use macros or inline functions from this file, or you compile
    this file and link it with other files to produce an executable, this
    file does not by itself cause the resulting executable to be covered by
    the GNU General Public License.  This exception does not however
    invalidate any other reasons why the executable file might be covered by
    the GNU General Public License.
*/
/**
 * @file GraphNode.hh
 *
 * Prototype of graph-based program representation: declaration of graph
 * node.
 *
 * @author Vladimir Guzma 2006 (vladimir.guzma@tut.fi)
 * @note rating: red
 */

#ifndef TTA_GRAPH_NODE_HH
#define TTA_GRAPH_NODE_HH

#include <string>

/**
 * Node of the graph-based program representation.
 */
class GraphNode {
public:
    // Client may give specific id. Those ID's must be unique.
    GraphNode(int nodeID) : nodeID_(nodeID) {}
    // Node id is autogenerated on this constructor
    GraphNode();
    virtual ~GraphNode();

    virtual GraphNode* clone() const;

    virtual int nodeID() const;
    virtual std::string toString() const;
    virtual std::string dotString() const;

    class Comparator {
    public:
        bool operator()(const GraphNode* gn1, const GraphNode* gn2) const;
    };
private:
    int nodeID_;
    static int idCounter_;
};

#endif
