DIST_OBJECTS = BinaryWriter.o TPEFWriter.o \
	SectionWriter.o \
	Section.o SectionElement.o \
	BinaryStream.o TPEFSectionWriter.o \
	SafePointer.o ReferenceKey.o \
	SafePointable.o Chunk.o \
	TPEFCodeSectionWriter.o \
	ValueReplacer.o FileOffsetReplacer.o \
	SectionOffsetReplacer.o \
	SectionSizeReplacer.o \
	MoveElement.o ImmediateElement.o \
	InstructionElement.o Binary.o \
	CodeSection.o DataSection.o \
	UDataSection.o TPEFDataSectionWriter.o \
	ASpaceElement.o TPEFStringSectionWriter.o \
	StringSection.o TPEFUDataSectionWriter.o \
	TPEFASpaceSectionWriter.o ASpaceSection.o \
	SectionIdReplacer.o SectionIndexReplacer.o \
	RelocSection.o TPEFRelocSectionWriter.o \
	RelocElement.o SymbolElement.o

TOP_SRCDIR = ../../../..
TOOL_OBJECTS = Exception.o Conversion.o Application.o

include ${TOP_SRCDIR}/test/Makefile_configure_settings
include ${TOP_SRCDIR}/test/Makefile_test.defs
