#!/bin/bash
#
# Script to build llvm pass plugins

if test $# -lt 2
then
    echo "Usage: buildllvmpass <object file> <source files>"
else
    compiler=gcc
    llvmlibs="-lLLVMCodeGen"
    llvmldflags=$(llvm-config --ldflags)
    llvmcppflags=$(llvm-config --cppflags)
    soflags="-O2 -lgcc -shared -static -g -fPIC -o"
    objectfile=$1
    shift
    $compiler $llvmcppflags $llvmldflags $llvmlibs $soflags $objectfile $* && \
        echo "Compilation successful." || echo "Compilation failed." >&2
fi
