
# relative path to Makefile definitions and shared latex/bibtex files
DEFS = ../../../latexdefs

# document title (extended document name) - must be double quoted!
DOC_NAME_TEXT = "TTA Instruction Scheduler"

# options passed to latex command
LATEX_OPTS = -interaction=batchmode

# default rule built by Makefile
BUILD_DEFAULT = pdf


include $(DEFS)/Makefile.defs

