DIST_OBJECTS = FileSystem.o Application.o Environment.o Conversion.o \
		Exception.o
TOP_SRCDIR = ../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings

EXTRA_LINKER_FLAGS = ${BOOST_LDFLAGS}

include ${TOP_SRCDIR}/test/Makefile_test.defs
