OBJECTS = OperationContext.o OperationPool.o Operation.o InstructionFormat.o RISCVTools.o \
Machine.o BEMGenerator.o BinaryEncoding.o RISCVFields.o RISCVInstructionExecutor.o

TOP_SRCDIR = ../../../..
include ${TOP_SRCDIR}/test/Makefile_test.defs
