#!/bin/bash
# Copyright 2002-2008 Tampere University.  All Rights Reserved.
#
# This file is part of TTA-Based Codesign Environment (TCE).
#
# TCE is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License version 2 as published by the Free
# Software Foundation.
#
# TCE is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# TCE; if not, write to the Free Software Foundation, Inc., 51 Franklin St,
# Fifth Floor, Boston, MA  02110-1301  USA
#
# As a special exception, you may use this file as part of a free software
# library without restriction.  Specifically, if other files instantiate
# templates or use macros or inline functions from this file, or you compile
# this file and link it with other files to produce an executable, this file
# does not by itself cause the resulting executable to be covered by the GNU
# General Public License.  This exception does not however invalidate any
# other reasons why the executable file might be covered by the GNU General
# Public License.

# Copy all headers into the installation prefix/include/tce directory.
# Headers are needed for TCE plugin development. This must be executed
# in the tce root directory.

TCEROOTPATH=${1:-/usr/local/tce}
progname=`basename $0`

function usage {
    echo "Copy all headers into the installation prefix/include/tce directory."
    echo "Headers are needed for TCE plugin development. This must be executed"
    echo "in the tce root directory."
    echo
    echo "The destination directory is found by using 'tce-config', so it has"
    echo "to be found in your PATH."
}

if [ "$1_" = "-h_" -o "$1_" = "--help_" ]
then
    usage ;
    exit 0 ;
fi

if [ "$1_" != "_" ]
then
    TCE_ROOT=$1
else
    if [ ! tce-config ]
    then
    	usage ;
    	exit 1
    fi
    TCE_ROOT=$(tce-config --prefix)
fi

if [ ! -d src -o ! -e configure ]
then
    usage ;
    exit 1;
fi


DESTINATION=${DESTDIR}${TCE_ROOT}/include/tce
mkdir -p $DESTINATION
cp `find src/ -name *.icc` $DESTINATION
cp `find src/ -name *.hh` $DESTINATION
cp config.h $DESTINATION
