#!/bin/bash

# Copy all headers into the installation prefix/include/tce directory.
# Headers are needed for TCE plugin development. This must be executed
# in the tce root directory.

TCEROOTPATH=${1:-/usr/local/tce}
progname=`basename $0`

function usage {
    echo "Copy all headers into the installation prefix/include/tce directory."
    echo "Headers are needed for TCE plugin development. This must be executed"
    echo "in the tce root directory."
    echo
    echo "The destination directory is found by using 'tce-config', so it has"
    echo "to be found in your PATH."
}

if [ "$1_" = "-h_" -o "$1_" = "--help_" ]
then
    usage ;
    exit 0 ;
fi

if [ "$1_" != "_" ]
then
    TCE_ROOT=$1
else
    if [ ! tce-config ]
    then
    	usage ;
    	exit 1
    fi
    TCE_ROOT=$(tce-config --prefix)
fi

if [ ! -d src -o ! -e configure ]
then
    usage ;
    exit 1;
fi


DESTINATION=${TCE_ROOT}/include/tce
mkdir -p $DESTINATION
cp `find src/ -name *.icc` $DESTINATION
cp `find src/ -name *.hh` $DESTINATION
cp config.h $DESTINATION
