/*
    Copyright 2002-2008 Tampere University of Technology.  All Rights
    Reserved.

    This file is part of TTA-Based Codesign Environment (TCE).

    TCE is free software; you can redistribute it and/or modify it under the
    terms of the GNU General Public License version 2 as published by the Free
    Software Foundation.

    TCE is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
    details.

    You should have received a copy of the GNU General Public License along
    with TCE; if not, write to the Free Software Foundation, Inc., 51 Franklin
    St, Fifth Floor, Boston, MA  02110-1301  USA

    As a special exception, you may use this file as part of a free software
    library without restriction.  Specifically, if other files instantiate
    templates or use macros or inline functions from this file, or you compile
    this file and link it with other files to produce an executable, this
    file does not by itself cause the resulting executable to be covered by
    the GNU General Public License.  This exception does not however
    invalidate any other reasons why the executable file might be covered by
    the GNU General Public License.
*/
/**
 * @file DOMBuilderErrorHandler.cc
 *
 * Implementation of DOMBuilderErrorHandler class.
 *
 * @author Lasse Laasonen 2004 (lasse.laasonen-no.spam-tut.fi)
 */

#include <xercesc/dom/DOMLocator.hpp>

#include "DOMBuilderErrorHandler.hh"
#include "Conversion.hh"

using std::string;

/**
 * Constructor.
 */
DOMBuilderErrorHandler::DOMBuilderErrorHandler() :
    errorCount_(0), errorLog_("") {
}


/**
 * Destructor.
 */
DOMBuilderErrorHandler::~DOMBuilderErrorHandler() {
}


/**
 * Handler function to process errors that occur while building DOM
 * documents.
 *
 * Stores information to locate the error (URI, line number, column,
 * diagnostic message) passed by a DOM builder to an error log.  Called by
 * DOMBuilder::parseURI.
 *
 * @param domError Error generated by DOM builder.
 * @return Always Boolean value 'true'.
 */
bool
DOMBuilderErrorHandler::handleError(const DOMError& domError) {

    errorCount_++;
    DOMLocator* locator = domError.getLocation();

    errorLog_ += "Error at file ";
    errorLog_ += Conversion::XMLChToString(locator->getURI());
    errorLog_ += ", line ";
    errorLog_ += Conversion::toString(locator->getLineNumber());
    errorLog_ += ", column ";
    errorLog_ += Conversion::toString(locator->getColumnNumber());
    errorLog_ += "\n    Message: ";
    errorLog_ += Conversion::XMLChToString(domError.getMessage());
    errorLog_ += "\n";

    return true;
}


/**
 * Returns the number of errors handled.
 *
 * @return Number of errors handled.
 */
int
DOMBuilderErrorHandler::errorCount() const {
    return errorCount_;
}


/**
 * Returns the error log.
 *
 * @return The error log.
 */
string
DOMBuilderErrorHandler::errorLog() const {
    return errorLog_;
}
