
# relative path to Makefile definitions and shared latex/bibtex files
DEFS = ../../../latexdefs

# base name of document to build and main latex source file
DOC_NAME = tce-frontend

# document title (extended document name) - must be double quoted!
DOC_NAME_TEXT = "TCE v1 Frontend Compiler"

# options passed to latex command
LATEX_OPTS = -interaction=batchmode

# name of the latex class file for this document (with relative path)
CLASS_PATH = ../../../latexdefs/design.cls

# default rule built by Makefile
BUILD_DEFAULT = pdf


include $(DEFS)/Makefile.defs
