DIST_OBJECTS = Conversion.o Exception.o Application.o
TOP_SRCDIR = ../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings

EXTRA_LINKER_FLAGS = ${BOOST_LDFLAGS}

include ${TOP_SRCDIR}/test/Makefile_test.defs