#!/bin/bash
# disable the test if GHDL is not installed on the machine
rm -rf *.disabled

ghdl_bin=$(which ghdl 2> /dev/null)
if [ "x${ghdl_bin}" == "x" ]; then
    touch tcetest_almaif_integrator.sh.disabled
fi
