DIST_OBJECTS = FiniteStateAutomaton.o FUFiniteStateAutomaton.o \
	CollisionMatrix.o ../mach/ResourceVector.o \
	../mach/ResourceVectorSet.o
TOOL_OBJECTS = *.o
MACH_OBJECTS = *.o
TOP_SRCDIR = ../../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings

EXTRA_LINKER_FLAGS = 
include ${TOP_SRCDIR}/test/Makefile_test.defs
