DIST_OBJECTS = OperationContext.o OperationState.o
TOOL_OBJECTS = Exception.o Application.o SimValue.o ObjectState.o \
	Conversion.o
MEMORY_OBJECTS = Memory.o 
TOP_SRCDIR = ../../../..
include ${TOP_SRCDIR}/test/Makefile_test.defs

