DIST_OBJECTS = Memory.o IdealSRAM.o
TOOL_OBJECTS = Application.o Exception.o Conversion.o
TOP_SRCDIR = ../../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings
include ${TOP_SRCDIR}/test/Makefile_test.defs
