DIST_OBJECTS = 	CodeSectionCreator.o DataSectionCreator.o LabelManager.o \
		MachineResourceManager.o AssemblerParser.o Assembler.o

MACH_OBJECTS = *.o
OSAL_OBJECTS = *.o
TOOL_OBJECTS = *.o
UMACH_LIB_OBJS = *.o
TPEF_OBJECTS = *.o
APPLIBS_MACH_OBJS = ResourceVector.o ResourceVectorSet.o

TOP_SRCDIR = ../../../..

include ${TOP_SRCDIR}/test/Makefile_configure_settings

EXTRA_LINKER_FLAGS = 
include ${TOP_SRCDIR}/test/Makefile_test.defs
