#!/bin/bash
CURDIR=$(pwd)
rm -rf growmachine.dsdb
rm -rf ?.{adf,tpef}

# Compile the initial machine generator estimator plugin.
pushd . > /dev/null
cd ../../../../../tce/explorer/ && rm -f *.so
../src/codesign/Explorer/buildexplorerplugin GrowMachine.so GrowMachine.cc > /dev/null
popd > /dev/null
