DIST_OBJECTS =	BinaryStream.o Section.o \
	      	SafePointer.o \
	      	SafePointable.o ReferenceKey.o \
	      	Chunk.o SectionElement.o \
		ASpaceElement.o


TOP_SRCDIR = ../../../..
TOOL_OBJECTS = Exception.o Conversion.o Application.o

include ${TOP_SRCDIR}/test/Makefile_configure_settings
include ${TOP_SRCDIR}/test/Makefile_test.defs
