DIST_OBJECTS = Application.o 
TOOL_OBJECTS = FileSystem.o Environment.o Conversion.o Exception.o
TOP_SRCDIR = ../../..
INITIALIZATION = init_test_scripts

include ${TOP_SRCDIR}/test/Makefile_test.defs

init_test_scripts:
	@chmod ugo+rx data/*.sh
