/*
    Copyright 2002-2008 Tampere University of Technology.  All Rights
    Reserved.

    This file is part of TTA-Based Codesign Environment (TCE).

    TCE is free software; you can redistribute it and/or modify it under the
    terms of the GNU General Public License version 2 as published by the Free
    Software Foundation.

    TCE is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
    details.

    You should have received a copy of the GNU General Public License along
    with TCE; if not, write to the Free Software Foundation, Inc., 51 Franklin
    St, Fifth Floor, Boston, MA  02110-1301  USA

    As a special exception, you may use this file as part of a free software
    library without restriction.  Specifically, if other files instantiate
    templates or use macros or inline functions from this file, or you compile
    this file and link it with other files to produce an executable, this
    file does not by itself cause the resulting executable to be covered by
    the GNU General Public License.  This exception does not however
    invalidate any other reasons why the executable file might be covered by
    the GNU General Public License.
*/
/**
 * @file ProDeOptionsDialog.cc
 *
 * Implementation of ProDeOptionsDialog class.
 *
 * @author Veli-Pekka J‰‰skel‰inen (vjaaskel@cs.tut.fi)
 * @note rating: red
 */

#include <boost/format.hpp>
#include <wx/notebook.h>
#include "ProDeOptionsDialog.hh"
#include "ProDeOptions.hh"
#include "WxConversion.hh"
#include "ProDe.hh"
#include "Conversion.hh"
#include "UserManualCmd.hh"
#include "WidgetTools.hh"
#include "GUITextGenerator.hh"
#include "ProDeTextGenerator.hh"
#include "ProDeConstants.hh"

using boost::format;
using std::string;
using std::vector;


BEGIN_EVENT_TABLE(ProDeOptionsDialog, OptionsDialog)
    EVT_BUTTON(wxID_OK, ProDeOptionsDialog::onOK)
END_EVENT_TABLE()


/**
 * The Constructor.
 *
 * @param parent Parent window of the dialog.
 * @param options Options to be modified.
 */
ProDeOptionsDialog::ProDeOptionsDialog(
    wxWindow* parent, ProDeOptions& options, CommandRegistry& registry):
    OptionsDialog(parent, options, registry),
    parent_(parent), options_(options) {

    wxPanel* generalPage = new wxPanel(notebook_, -1);
    createGeneralPage(generalPage, true, true);
    addPage(generalPage, _T("General"));

    undoStackSize_ = dynamic_cast<wxSpinCtrl*>(FindWindow(ID_UNDO_LEVELS));

    readProDeOptions();

}


/**
 * The Destructor.
 */
ProDeOptionsDialog::~ProDeOptionsDialog() {
}

/**
 * Reads the options in options_ to dialog attributes.
 */
void
ProDeOptionsDialog::readProDeOptions() {
    undoStackSize_->SetValue(options_.undoStackSize());
}


/**
 * Writes the options from dialog attributes to the current options object.
 */
void
ProDeOptionsDialog::writeProDeOptions() {
    options_.setUndoStackSize(undoStackSize_->GetValue());
}


/**
  * Validates input in the controls, and updates the options.
  */
void
ProDeOptionsDialog::onOK(wxCommandEvent&) {

    if (!Validate()) {
        return;
    }

    if (!TransferDataFromWindow()) {
        return;
    }

    writeOptions();
    writeProDeOptions();

    EndModal(wxID_OK);
}


/**
 * Creates the 'General' page for the dialog.
 *
 * This function was initially generated by wxDesigner.
 * @return Main sizer of the created contents.
 * @param parent The dialog window.
 * @param call_fit If true, fits the contents inside the dialog.
 * @param set_sizer If true, sets the main sizer as dialog contents.
 */
wxSizer*
ProDeOptionsDialog::createGeneralPage(
    wxWindow *parent, bool call_fit, bool set_sizer ) {

    wxBoxSizer *item0 = new wxBoxSizer( wxHORIZONTAL );

    item0->Add( 50, 20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item1 = new wxStaticText( parent, ID_LABEL_UNDO_LEVELS, wxT("Undo levels:"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item2 = new wxSpinCtrl( parent, ID_UNDO_LEVELS, wxT("1"), wxDefaultPosition, wxSize(100,-1), 0, 1, 100, 0 );
    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }

    return item0;
}
